### ISSUE TITLE
node-gyp error

### ISSUE THREAD

**Issue by m1ga** [appcelerator/node-ios-device#5]
When trying to install tio2 I receive this error:

~~~
> ti-mocha@0.1.3 install /lib/node_modules/tio2/node_modules/ti-mocha
> node ./lib/install.js

 
> node-ios-device@0.3.2 install /lib/node_modules/tio2/node_modules/ioslib/node_modules/node-ios-device
> node-gyp rebuild

gyp: binding.gyp not found (cwd: /usr/lib/node_modules/tio2/node_modules/ioslib/node_modules/node-ios-device) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.0.4-303.fc22.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
ERR! cwd /usr/lib/node_modules/tio2/node_modules/ioslib/node_modules/node-ios-device
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 4.0.4-303.fc22.x86_64
npm ERR! argv "node" "/bin/npm" "install" "-g" "tio2"
npm ERR! node v0.10.36
npm ERR! npm  v2.11.0
npm ERR! code ELIFECYCLE

npm ERR! node-ios-device@0.3.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-ios-device@0.3.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-ios-device package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-ios-device
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
~~~

> node-gyp --version
v2.0.1

> node --version
v0.10.36

> npm --version
2.11.0

its fails at node-ios-device so I think the issue belongs here

**Comment by cb1kenobi** [comment]
That's because tio2 is using an old version of ioslib which has an old version of node-ios-device. node-ios-device v0.4.1 has already been published and fixes the issue above. However the newest version of ioslib with node-ios-device v0.4.1 has not been published. I expect it to be published in the next 36 hours.

**Comment by m1ga** [comment]
:+1:  thank you
